### ISSUE TITLE
Suggestion: Auto-kill onLoad and reverse

### ISSUE THREAD

**Issue by Dynalon** [eemeli/chrome-kill-sticky#1]
Hi, this is a great addon! Especially since this GDPR banner nagging allday

Here a suggestion: Add an option to enable it by default on every page onload, and add a key combination to undo this.

**Comment by eemeli** [comment]
A PR to that effect would be welcome, but my suspicion is that it'd be too difficult to get right to be worth the effort. Essentially, the current "undo" for the plugin is to reload the page, and that allows for the "kill" action to just brute-force remove everything sticky. Enabling it to run at onLoad by default would require for the elements to be held in some memory, and to have some rather complex (and therefore failure-prone) logic driving their re-entry to the page.

**Comment by Dynalon** [comment]
See pr #2
