### ISSUE TITLE
Suggestion: Sites to ignore or custom shortcut

### ISSUE THREAD

**Issue by truthdoug** [eemeli/chrome-kill-sticky#5]
When composing email on gmail, the shortcut cmd+k (mac) is used to add a link to the selected text. When chrome-kill-sticky is installed, its use of cmd+k takes precedence.

Options to remedy:
- Add user option to define a list of sites to ignore (start with chrome guidelines on [user options](https://developer.chrome.com/extensions/getstarted#options) in extension)
- Add user option to choose a different keyboard shortcut

**Comment by eemeli** [comment]
Have you tried to customise the shortcut using the instructions from the readme?
> To change the keyboard shortcut, visit the page `chrome://extensions/shortcuts.`

**Comment by truthdoug** [comment]
D'oh!

Thanks for bringing that to my attention. That works.
